apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maryshopping-postgres-pv-claim
  namespace: postgres
  labels:
    app: maryshopping-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi