version: "3.9"

services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: postgres_maryshopping_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: maryshopping
      POSTGRES_PASSWORD: maryshopping
      POSTGRES_DB: maryshopping
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
